# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d07bdb687ddf97dde6a83e73298c40450b521e9d6890e45e898f016ef984f61c1ab90a2c5becbf9dcf6308227245f0fcd37c1d88b18385dc0ede3911f1a689b

test:
  secret_key_base: b0a3ef0f033a2fae09f15312961684013054c6a7c1c66ebd031ccc1be3fd017853565cb8e2281a9aba079b3c18e4940ee51e68b4b860238cf8e07bad055dcd32

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
